"""copy_table

Revision ID: 0a27faf05468
Revises: 6d37c4578b17
Create Date: 2018-06-18 13:29:32.548567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a27faf05468'
down_revision = '6d37c4578b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_serial_number', sa.String(length=30), nullable=True),
    sa.Column('date_acquired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copy')
    # ### end Alembic commands ###
