"""add book_id

Revision ID: 70d12de357e5
Revises: 0a27faf05468
Create Date: 2018-06-19 14:23:38.451780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d12de357e5'
down_revision = '0a27faf05468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'copy', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'copy', type_='foreignkey')
    op.drop_column('copy', 'book_id')
    # ### end Alembic commands ###
