"""set_constraints_on_patrons

Revision ID: 7cdcdc013b46
Revises: f069cedd01f4
Create Date: 2018-06-21 15:27:17.476706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdcdc013b46'
down_revision = 'f069cedd01f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patron', 'id_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('patron', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('patron', 'surname',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_index('ix_patron_email', table_name='patron')
    op.create_index(op.f('ix_patron_email'), 'patron', ['email'], unique=True)
    op.drop_index('ix_patron_id_number', table_name='patron')
    op.create_index(op.f('ix_patron_id_number'), 'patron', ['id_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patron_id_number'), table_name='patron')
    op.create_index('ix_patron_id_number', 'patron', ['id_number'], unique=False)
    op.drop_index(op.f('ix_patron_email'), table_name='patron')
    op.create_index('ix_patron_email', 'patron', ['email'], unique=False)
    op.alter_column('patron', 'surname',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('patron', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('patron', 'id_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
