"""add_created_and_modified_to_all_tables

Revision ID: f069cedd01f4
Revises: d259a9b36d3a
Create Date: 2018-06-21 14:50:11.966461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f069cedd01f4'
down_revision = 'd259a9b36d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('author', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('book', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('book', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('copy', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('copy', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy', 'last_updated')
    op.drop_column('copy', 'created_on')
    op.drop_column('book', 'last_updated')
    op.drop_column('book', 'created_on')
    op.drop_column('author', 'last_updated')
    op.drop_column('author', 'created_on')
    # ### end Alembic commands ###
